table kmeans_assignments
	lineageTag: ecd15c4d-c500-49c6-9375-08fdcef4f3cf

	column incident_id
		dataType: string
		lineageTag: f6a54694-fec8-4627-9a09-d17bc816d281
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column cluster_pred
		dataType: int64
		formatString: 0
		lineageTag: 6b63e441-e123-4604-89a9-bd0441773616
		summarizeBy: sum
		sourceColumn: cluster_pred

		annotation SummarizationSetBy = Automatic

	column cluster_label
		dataType: string
		lineageTag: 9b90a417-aa60-43b5-a445-1d83a367b9c1
		summarizeBy: none
		sourceColumn: cluster_label

		annotation SummarizationSetBy = Automatic

	partition kmeans_assignments = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("D:\Projetos\AWS_Portifolio\Projeto aws\data"),
				    #"D:\Projetos\AWS_Portifolio\Projeto aws\data\ml\kmeans\_kmeans_cluster_assignments csv" = Fonte{[#"Folder Path"="D:\Projetos\AWS_Portifolio\Projeto aws\data\ml\kmeans\",Name="kmeans_cluster_assignments.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"D:\Projetos\AWS_Portifolio\Projeto aws\data\ml\kmeans\_kmeans_cluster_assignments csv",[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"CSV Importado", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"incident_id", type text}, {"cluster_pred", Int64.Type}, {"cluster_label", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

