#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Corrige notebook 07 — Feature Selection CAUSA/EFEITO sem emojis
"""

import json

# Carregar notebook
nb_path = 'notebooks/07_model_clustering_kmeans.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

print("[OK] Notebook carregado: %d celulas" % len(nb['cells']))

# ===== CELL 3B: EDA SEM EMOJIS =====
cell_3b = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== [3b] EDA: ANALISE DOS DADOS ANTES DE TRANSFORMACAO =====\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "# CAUSA: Features de ENTRADA\n",
        "cause_cols = [\n",
        "    'prioridade_num', 'grupo_designado', 'categoria', 'subcategoria', 'produto',\n",
        "    'hora_abertura', 'turno_abertura', 'dia_semana_num', 'fora_horario_comercial',\n",
        "    'abriu_fim_de_semana', 'mes_abertura', 'trimestre', 'possui_pai', 'triagem_incompleta'\n",
        "]\n",
        "\n",
        "# EFEITO: Features de SAIDA (EXCLUIR do treino)\n",
        "effect_cols = [\n",
        "    'duracao_horas', 'horas_ate_resolucao', 'foi_resolvido', 'excedeu_tempo_esperado',\n",
        "    'fechado_sem_tecnico', 'target_risco_sla', 'score_risco_operacional'\n",
        "]\n",
        "\n",
        "# EXCLUIR: NULL placeholders, redundantes\n",
        "exclude_cols = [\n",
        "    'incident_id', 'cluster', 'data_abertura',\n",
        "    'duracao_horas_scaled', 'cluster_id',\n",
        "    'is_filho_de_problema'\n",
        "]\n",
        "\n",
        "print('[STATS] ESTRUTURA DE FEATURES:')\n",
        "print('   [OK] CAUSA (incluir): %d colunas' % len(cause_cols))\n",
        "print('   [WARN] EFEITO (interpretar): %d colunas' % len(effect_cols))\n",
        "print('   [ERROR] EXCLUIR: %d colunas' % len(exclude_cols))\n",
        "print('   Total dataset: %d' % len(df.columns))\n",
        "\n",
        "# EDA com 6 graficos\n",
        "fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n",
        "fig.suptitle('EDA: Analise de Features ANTES de Transformacao', fontsize=14, fontweight='bold')\n",
        "\n",
        "# [1] Cardinalidade\n",
        "cat_cols_all = df.select_dtypes(include=['object']).columns.tolist()\n",
        "cardinality = {col: df[col].nunique() for col in cat_cols_all}\n",
        "cardinality_sorted = dict(sorted(cardinality.items(), key=lambda x: x[1], reverse=True))\n",
        "axes[0, 0].barh(list(cardinality_sorted.keys()), list(cardinality_sorted.values()), color='steelblue')\n",
        "axes[0, 0].set_xlabel('Numero de Valores Unicos')\n",
        "axes[0, 0].set_title('1. Cardinalidade - Colunas Categoricas')\n",
        "axes[0, 0].grid(axis='x', alpha=0.3)\n",
        "\n",
        "# [2] Distribuicao\n",
        "cause_numeric = [c for c in cause_cols if c in df.columns and df[c].dtype in ['int64', 'float64']]\n",
        "sample_cause = cause_numeric[:4] if len(cause_numeric) >= 4 else cause_numeric\n",
        "if sample_cause:\n",
        "    df[sample_cause].hist(ax=axes[0, 1], bins=30, color='green', alpha=0.7, edgecolor='black')\n",
        "axes[0, 1].set_title('2. Distribuicao - Features CAUSA (amostra)')\n",
        "axes[0, 1].grid(alpha=0.3)\n",
        "\n",
        "# [3] Correlacao\n",
        "if len(cause_numeric) > 1:\n",
        "    corr_matrix = df[cause_numeric].corr()\n",
        "    sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0, \n",
        "                ax=axes[0, 2], cbar_kws={'label': 'Correlacao'})\n",
        "axes[0, 2].set_title('3. Correlacao - Features CAUSA')\n",
        "\n",
        "# [4] NULL values\n",
        "null_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)\n",
        "null_pct = null_pct[null_pct > 0]\n",
        "if len(null_pct) > 0:\n",
        "    axes[1, 0].barh(null_pct.index, null_pct.values, color='coral')\n",
        "    axes[1, 0].set_xlabel('Percentual de NULLs')\n",
        "axes[1, 0].set_title('4. Valores NULL')\n",
        "axes[1, 0].grid(axis='x', alpha=0.3)\n",
        "\n",
        "# [5] Categoria distribution\n",
        "if 'categoria' in df.columns:\n",
        "    categoria_dist = df['categoria'].value_counts().head(15)\n",
        "    axes[1, 1].barh(categoria_dist.index, categoria_dist.values, color='mediumseagreen')\n",
        "    axes[1, 1].set_xlabel('Contagem')\n",
        "axes[1, 1].set_title('5. Top-15 Categorias')\n",
        "axes[1, 1].grid(axis='x', alpha=0.3)\n",
        "\n",
        "# [6] Summary\n",
        "axes[1, 2].axis('off')\n",
        "summary = ('RESUMO DE FEATURES:\\n\\n'\n",
        "          '[OK] CAUSA: %d colunas\\n'\n",
        "          '     Objetivo: Perfil entrada\\n\\n'\n",
        "          '[WARN] EFEITO: %d colunas\\n'\n",
        "          '      Objetivo: Interpretar\\n\\n'\n",
        "          '[ERROR] EXCLUIR: %d\\n'\n",
        "          '        Data leakage/NULL') % (len(cause_cols), len(effect_cols), len(exclude_cols))\n",
        "axes[1, 2].text(0.05, 0.95, summary, transform=axes[1, 2].transAxes,\n",
        "                fontsize=10, verticalalignment='top', fontfamily='monospace',\n",
        "                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))\n",
        "axes[1, 2].set_title('6. Estrategia de Feature Selection', fontweight='bold')\n",
        "\n",
        "plt.tight_layout()\n",
        "eda_path = os.path.join(Path(r'D:\\Projetos\\AWS_Portifolio\\Projeto aws\\data\\ml\\kmeans'), 'eda_feature_selection.png')\n",
        "Path(eda_path).parent.mkdir(parents=True, exist_ok=True)\n",
        "fig.savefig(eda_path, dpi=100, bbox_inches='tight')\n",
        "plt.close()\n",
        "\n",
        "print('[OK] EDA salva em: %s' % eda_path)\n"
    ]
}

# ===== CELL 4: Feature Engineering SEM EMOJIS =====
cell_4_new = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== [4] FEATURE ENGINEERING: SELECAO CAUSA + ENCODING OTIMIZADO =====\n",
        "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
        "from sklearn.decomposition import PCA\n",
        "\n",
        "print('[INFO] FEATURE ENGINEERING: CAUSA + ENCODING OTIMIZADO')\n",
        "\n",
        "# ===== OUTLIER REMOVAL (OR LOGICO) =====\n",
        "numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()\n",
        "numeric_cols = [c for c in numeric_cols if c not in ['incident_id', 'cluster', 'data_abertura']]\n",
        "\n",
        "print('[STATS] Dataset Original: %d incidentes' % len(df))\n",
        "\n",
        "# Outlier detection com OR logico\n",
        "outlier_counts = pd.DataFrame(index=df.index)\n",
        "for col in numeric_cols:\n",
        "    Q1 = df[col].quantile(0.25)\n",
        "    Q3 = df[col].quantile(0.75)\n",
        "    IQR = Q3 - Q1\n",
        "    lower = Q1 - 1.5 * IQR\n",
        "    upper = Q3 + 1.5 * IQR\n",
        "    outlier_counts[col] = ~((df[col] >= lower) & (df[col] <= upper))\n",
        "\n",
        "outlier_total_per_row = outlier_counts.sum(axis=1)\n",
        "max_outliers_allowed = len(numeric_cols) * 0.5\n",
        "outlier_mask = outlier_total_per_row <= max_outliers_allowed\n",
        "\n",
        "df_clean = df[outlier_mask].copy()\n",
        "n_removed = len(df) - len(df_clean)\n",
        "\n",
        "print('[STATS] Outlier Detection - Removidos: %d (%.2f%%)' % (n_removed, n_removed/len(df)*100))\n",
        "print('        Mantidos: %d (%.2f%%)' % (len(df_clean), len(df_clean)/len(df)*100))\n",
        "\n",
        "# ===== SELECIONAR FEATURES CAUSA =====\n",
        "cause_cols = [\n",
        "    'prioridade_num', 'grupo_designado', 'categoria', 'subcategoria', 'produto',\n",
        "    'hora_abertura', 'turno_abertura', 'dia_semana_num', 'fora_horario_comercial',\n",
        "    'abriu_fim_de_semana', 'mes_abertura', 'trimestre', 'possui_pai', 'triagem_incompleta'\n",
        "]\n",
        "\n",
        "cause_cols_valid = [c for c in cause_cols if c in df_clean.columns]\n",
        "print('[OK] Features CAUSA validas: %d' % len(cause_cols_valid))\n",
        "\n",
        "df_features = df_clean[cause_cols_valid].copy()\n",
        "\n",
        "# ===== ENCODING CICLICO =====\n",
        "print('[INFO] Encoding Ciclico para Features Temporais')\n",
        "temporal_cyclic = {\n",
        "    'hora_abertura': 24,\n",
        "    'dia_semana_num': 7,\n",
        "    'mes_abertura': 12\n",
        "}\n",
        "\n",
        "for col, period in temporal_cyclic.items():\n",
        "    if col in df_features.columns:\n",
        "        df_features[f'{col}_sin'] = np.sin(2 * np.pi * df_features[col] / period)\n",
        "        df_features[f'{col}_cos'] = np.cos(2 * np.pi * df_features[col] / period)\n",
        "        df_features = df_features.drop(columns=[col])\n",
        "\n",
        "# ===== FREQUENCY ENCODING =====\n",
        "print('[INFO] Frequency Encoding para Alta Cardinalidade')\n",
        "high_cardinality_cols = ['grupo_designado', 'subcategoria', 'produto']\n",
        "\n",
        "for col in high_cardinality_cols:\n",
        "    if col in df_features.columns:\n",
        "        freq_map = df_features[col].value_counts(normalize=True).to_dict()\n",
        "        df_features[col] = df_features[col].map(freq_map).fillna(0)\n",
        "\n",
        "# ===== ONE-HOT ENCODING =====\n",
        "print('[INFO] One-Hot Encoding para Baixa Cardinalidade')\n",
        "low_cardinality_cols = ['categoria', 'turno_abertura']\n",
        "low_cardinality_cols = [c for c in low_cardinality_cols if c in df_features.columns]\n",
        "\n",
        "if low_cardinality_cols:\n",
        "    for col in low_cardinality_cols:\n",
        "        df_features[col] = df_features[col].fillna('unknown').astype(str)\n",
        "    \n",
        "    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore', max_categories=50)\n",
        "    X_ohe = encoder.fit_transform(df_features[low_cardinality_cols])\n",
        "    feature_names_ohe = encoder.get_feature_names_out(low_cardinality_cols)\n",
        "    X_ohe_df = pd.DataFrame(X_ohe, columns=feature_names_ohe, index=df_features.index)\n",
        "    \n",
        "    df_features = df_features.drop(columns=low_cardinality_cols)\n",
        "    df_features = pd.concat([df_features, X_ohe_df], axis=1)\n",
        "\n",
        "# ===== STANDARDSCALER =====\n",
        "print('[INFO] StandardScaler Normalization')\n",
        "scaler = StandardScaler()\n",
        "X_scaled = scaler.fit_transform(df_features.fillna(0))\n",
        "\n",
        "reduction_pct = (1 - X_scaled.shape[1]/680)*100\n",
        "print('[OK] Features Finais: %d (reducao de %.1f%%)' % (X_scaled.shape[1], reduction_pct))\n"
    ]
}

# ===== CELL 4B: Feature Selection Impact =====
cell_4b = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ===== [4b] VISUALIZACAO: Feature Selection Impact =====\n",
        "print('[INFO] VISUALIZACAO: Feature Selection Impact')\n",
        "\n",
        "fig, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
        "fig.suptitle('Feature Selection Impact: CAUSA + Encoding Otimizado', fontsize=14, fontweight='bold')\n",
        "\n",
        "# [1] Features Antes vs Depois\n",
        "features_comparison = ['Antes (OHE Explosion)', 'Depois (CAUSA only)']\n",
        "features_count = [680, X_scaled.shape[1]]\n",
        "colors_comp = ['#E53935', '#43A047']\n",
        "bars = axes[0].bar(features_comparison, features_count, color=colors_comp, edgecolor='black', linewidth=2)\n",
        "axes[0].set_ylabel('Numero de Features', fontweight='bold')\n",
        "axes[0].set_title('1. Reducao de Features')\n",
        "axes[0].grid(axis='y', alpha=0.3)\n",
        "for bar, count in zip(bars, features_count):\n",
        "    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 20,\n",
        "                str(count), ha='center', va='bottom', fontweight='bold', fontsize=11)\n",
        "\n",
        "# [2] Pie Chart\n",
        "removed_count = 680 - X_scaled.shape[1]\n",
        "kept_count = X_scaled.shape[1]\n",
        "sizes = [kept_count, removed_count]\n",
        "labels_pie = ['Mantidas (%d)' % kept_count, 'Removidas (%d)' % removed_count]\n",
        "colors_pie = ['#43A047', '#E53935']\n",
        "axes[1].pie(sizes, labels=labels_pie, colors=colors_pie, autopct='%1.1f%%',\n",
        "           startangle=90, textprops={'fontsize': 10, 'weight': 'bold'})\n",
        "axes[1].set_title('2. Features Removidas vs Mantidas')\n",
        "\n",
        "# [3] Correlacao\n",
        "if X_scaled.shape[1] > 1:\n",
        "    X_scaled_df = pd.DataFrame(X_scaled)\n",
        "    corr_post = X_scaled_df.corr()\n",
        "    corr_sample = corr_post.iloc[:min(15, len(corr_post)), :min(15, len(corr_post))]\n",
        "    sns.heatmap(corr_sample, annot=False, cmap='coolwarm', center=0,\n",
        "               ax=axes[2], cbar_kws={'label': 'Correlacao'}, vmin=-1, vmax=1)\n",
        "    axes[2].set_title('3. Correlacao Pos-Selecao')\n",
        "\n",
        "plt.tight_layout()\n",
        "feat_selection_path = os.path.join(Path(r'D:\\Projetos\\AWS_Portifolio\\Projeto aws\\data\\ml\\kmeans'), 'feature_selection_impact.png')\n",
        "fig.savefig(feat_selection_path, dpi=100, bbox_inches='tight')\n",
        "plt.close()\n",
        "\n",
        "print('[OK] Feature Selection Impact salva')\n"
    ]
}

# ===== INSERIR CELULAS =====
nb['cells'].insert(4, cell_3b)
nb['cells'][5] = cell_4_new
nb['cells'].insert(6, cell_4b)

print("[OK] Celulas inseridas/reescritas")

# ===== SALVAR =====
with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("[OK] Notebook salvo com sucesso!")
print("     Total de celulas: %d" % len(nb['cells']))
