version: 2

models:
  - name: ml_base_features
    description: "Tabela mestre de features (Feature Store) contendo dados limpos, enriquecidos e filtrados exclusivamente para consumo dos modelos preditivos e analíticos em Python."
    columns:
      - name: incident_id
        description: "Código original único do incidente (Chave Primária Comercial)."
        tests:
          - unique
          - not_null