name: 'aiops_locaweb'
version: '1.0.0'
config-version: 2

profile: 'aiops_locaweb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aiops_locaweb:
    staging:
      +materialized: view

    silver:
      +materialized: table
      +schema: silver

    gold:
      bi:
        +materialized: table
        +schema: gold_bi
      ml:
        +materialized: table
        +schema: gold_ml